[[documentation]]
= Spring Cloud Sleuth Documentation

include::_attributes.adoc[]

This section provides a brief overview of {project-full-name} reference documentation.
It serves as a map for the rest of the document.

[[sleuth-documentation-about]]
== About the Documentation

The {project-full-name} reference guide is available as

* {docs-url}/reference/html[Multi-page HTML]
* {docs-url}/reference/htmlsingle[Single-page HTML]
* {docs-url}/reference/pdf/{project-name}.pdf[PDF]

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.

[[documentation-getting-help]]
== Getting Help

If you have trouble with {project-full-name}, we would like to help.

* Try the <<howto.adoc#howto, How-to documents>>.
They provide solutions to the most common questions.
* Learn the {project-full-name} basics.
If you are starting out with {project-full-name}, try one of the https://spring.io/guides[guides].
* Ask a question.
We monitor https://stackoverflow.com[stackoverflow.com] for questions tagged with https://stackoverflow.com/tags/{project-name}[`{project-name}`].
* Report bugs with {project-full-name} at https://github.com/spring-cloud/{project-name}/issues.
* Chat with us at http://https://gitter.im/spring-cloud/{project-name}[{project-full-name} Gitter]

NOTE: All of {project-full-name} is open source, including the documentation.
If you find problems with the docs or if you want to improve them, please {github-code}[get involved].

[[sleuth-documentation-first-steps]]
== First Steps

If you are getting started with {project-full-name} or 'Spring' in general, start with
<<getting-started.adoc#getting-started, the following topics>>:

* *From scratch:* <<getting-started.adoc#getting-started-introducing-spring-cloud-sleuth, Overview>>
* *Tutorial:* <<getting-started.adoc#getting-started-first-application, Part 1>> | <<getting-started.adoc#getting-started-first-application-code, Part 2>>
* *Running your example:* <<getting-started.adoc#getting-started-first-application-run, Part 1>>

[[sleuth-documentation-working-with-sleuth]]
== Working with {project-full-name}

Ready to actually start using {project-full-name}? <<using.adoc#using, We have you covered>>:

* <<using.adoc#using-span-lifecycle,Span Lifecycle with Spring Cloud Sleuth's API>>
* <<using.adoc#using-naming-spans,Naming Spans>>
* <<using.adoc#using-annotations,Managins Spans with Annotations>>

[[sleuth-documentation-features]]
== Learning about {project-full-name} Features

Need more details about {project-full-name}'s core features?
<<project-features.adoc#features, The following content is for you>>:

* *Core Features:*
<<project-features.adoc#features-context-propagation, Context Propagation>> |
<<project-features.adoc#features-sampling, Sampling>>
<<project-features.adoc#features-baggage, Baggage>>

* *Tracer Features:*
<<project-features.adoc#features-brave, OpenZipkin Brave>>

* *Reporting Features:*
<<project-features.adoc#features-zipkin, Zipkin>> |
<<project-features.adoc#features-log-integration, Logs>>

[[sleuth-documentation-integration]]
== Integrations Topics

Finally, we have topics related to instrumentation integrations:

* *Integrations:*
<<integrations.adoc#sleuth-kafka-integration, Apache Kafka>> |
<<integrations.adoc#sleuth-async-integration, Asynchronous Communication>> |
<<integrations.adoc#sleuth-http-client-integration, HTTP Client Integration>> |
<<integrations.adoc#sleuth-http-server-integration, HTTP Server Integration>> |
<<integrations.adoc#sleuth-messaging-integration, Messaging>> |
<<integrations.adoc#sleuth-openfeign-integration, OpenFeign>> |
<<integrations.adoc#sleuth-opentracing-integration, OpenTracing>> |
<<integrations.adoc#sleuth-reactor-integration, Reactor>> |
<<integrations.adoc#sleuth-redis-integration, Redis>> |
<<integrations.adoc#sleuth-rpc-integration, RPC>> |
<<integrations.adoc#sleuth-rpc-grpc-integration, gRPC>> |
<<integrations.adoc#sleuth-rpc-dubbo-integration, Dubbo>> |
<<integrations.adoc#sleuth-runnablecallable-integration, Runnable and Callable>> |
<<integrations.adoc#sleuth-rxjava-integration, RxJava>> |
<<integrations.adoc#sleuth-circuitbreaker-integration, Spring Cloud CircuitBreaker>> |
<<integrations.adoc#sleuth-quartz-integration, Quartz>>
